[tool.poetry]
name = "mathelics"
version = "0.1.0"
description = ""
authors = ["afisher1"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cheader2json = "^0.0.0rc2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
