[tool.poetry]
name = "mathelics"
version = "0.1.0"
description = ""
authors = ["afisher1"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cffi = "^1.15.1"
clang = "14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
